# compush makefile

i:
	cp config.h config_def.h
	cp main.cpp main_def.cpp
	cp com.cpp com_def.cpp
	g++ main.cpp -g -o main 
	#g++ com.cpp -g -o com
	gcc com.c -g -o com
	gcc compression.c -lz -o compression
	gcc jie.c -lz -o jie
config:
	cp config.h config_def.h
	cp main.cpp main_def.cpp
